module.exports = {
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_CONFIRM: "ORDER_CONFIRM",
  ORDER_PROCESSING: "ORDER_PROCESSING",
  ORDER_APPROVED: "ORDER_APPROVED",
  ORDER_EXPORTED: "ORDER_EXPORTED",
  ORDER_SENT: "ORDER_SENT",
  ORDER_PAYMENT: "ORDER_PAYMENT",
  ORDER_COMPLETED: "ORDER_COMPLETED",
  ORDER_HOLD_ORDER: "ORDER_HOLD_ORDER",
  ORDER_HOLD_MONEY: "ORDER_HOLD_MONEY",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_RETURN: "ORDER_RETURN",
};
